### ISSUE TITLE
ReSmoked icon on post

### ISSUE THREAD

**Issue by baabeetaa** [smokenetwork/webapp#13]
![](https://cdn.discordapp.com/attachments/492437539592994837/493950270183833610/unknown.png)

PP proposes: 
1) Moving the post time under the username (space is already there based on mine wrapping down)
2) Adding a "ReSmoked" icon to the upper right corner to identify shared posts. (with mouse-over text )

![](https://cdn.discordapp.com/attachments/492437539592994837/493950698157768719/ReSmoked-Icon.png)

**Comment by anxiousstoner** [comment]
#31
