### ISSUE TITLE
Add robots meta tags to noindex certain profile pages for SEO

### ISSUE THREAD

**Issue by vikingcc** [smokenetwork/webapp#27]
Code to add to header:

`<meta name="robots" content="noindex,follow"/>`

Pages to add for each user ( @smoke as example user):

https://smoke.io/@smoke/permissions
https://smoke.io/@smoke/followed
https://smoke.io/@smoke/transfers
https://smoke.io/@smoke/password
https://smoke.io/@smoke/followers

**Comment by vikingcc** [comment]
@baabeetaa @anxiousstoner Does this make sense? Updated the code bit so it is showing properly now

**Comment by baabeetaa** [comment]
update it to `https://github.com/smokenetwork/webapp/blob/dev/src/app/utils/ExtractMeta.js#L23`?
