### ISSUE TITLE
Add a note about plagiarism to add post screen below content box / post button

### ISSUE THREAD

**Issue by vikingcc** [smokenetwork/webapp#36]
'Please remember to read our community [content guidelines](https://docs.smoke.io/#/contentguidelines) before posting content. Copying and pasting content from other sites without crediting the author is not allowed and is a form of plagiarism which will be penalized by the community. To earn Smoke create original content. '

**Comment by vikingcc** [comment]
@anxiousstoner What do you think of this idea to stop people from just copy and pasting blindly like a lot of accounts are still doing?

**Comment by anxiousstoner** [comment]
Done #48
