### ISSUE TITLE
Don't show comments posted from a different app

### ISSUE THREAD

**Issue by anxiousstoner** [smokenetwork/webapp#40]
We should stop displaying posts/comments that are posted using a different app meta so that only posts posted thru smoke.io (or using the smokeio meta, display on smoke.io. )

This will improve SEO (as crosspost apps wont show up, decreasing duplicate content) and allow 3rd party dapps such as tradeitforweed to develop unique content.

**Comment by staccDOTsol** [comment]
Changed smoke post + comment app=smoke/0.1
